// // BUILT IN TIPTAP EXTENSIONS
// import {
//   HorizontalRule,
//   OrderedList,
//   BulletList,
//   CodeBlock,
//   HardBreak,
//   ListItem,
//   TodoItem,
//   TodoList,
//   Image,
//   Bold,
//   Strike,
//   Italic,
//   Underline,
//   Code,
//   Link,
//   Table,
//   TableHeader,
//   TableCell,
//   TableRow,
//   History,
// } from 'tiptap-extensions';

// // CUSTOMIZED EXTENSIONS
// import {
//   Blockquote,
//   Superscript,
//   Alignment,
//   TextColor,
//   Paragraph,
//   Heading,
//   FormatClear,
//   Indent,
//   FontSize,
//   FontType,
// } from '@components/tiptap/extensions';

// export const EXTENSIONS = [
//   new Blockquote(),
//   new Superscript(),
//   new Alignment(),
//   new TextColor(),
//   new Paragraph(),
//   new Heading({ levels: [1, 2, 3] }),
//   new FormatClear(),
//   new Indent(),
//   new FontSize(),
//   new FontType(),

//   // BUILT IN EXTENSIONS
//   new HorizontalRule(),
//   new CodeBlock(),
//   new HardBreak(),
//   new BulletList(),
//   new OrderedList(),
//   new ListItem(),
//   new TodoItem({
//     nested: true,
//   }),
//   new TodoList(),
//   new Bold(),
//   new Code(),
//   new Italic(),
//   new Link(),
//   new Image(),
//   new Table(),
//   new TableHeader(),
//   new TableCell(),
//   new TableRow(),
//   new Strike(),
//   new Underline(),
//   new History(),
// ];
